
[workspace]
members = [
    "day-one",
    "day-two",
    "day-three",
    "day-four",
    "day-five",
    "day-six",
    "day-nine",
    # "day-seven",
    # "day-eight",
    # "day-ten",
    # "day-twentyfour",
]
